version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: park-mysql
    environment:
      MYSQL_DATABASE: parkdb
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: parkuser
      MYSQL_PASSWORD: parkpass
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  app:
    build: .
    container_name: park-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/park-api?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL-AUTO: update
    ports:
      - "8080:8080"
    restart: unless-stopped

volumes:
  mysql_data: