apiVersion: v1
kind: Service
metadata:
  name: park-api-service
spec:
  type: NodePort
  selector:
    app: park-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080